[section {Changes for version 3.1.9 to be}]
[list_begin enumerated]

[enum]	Fixed issue #31. Accepted patch by Andrew Shadoura, with
	changes (comments), for easier integration of critcl with
	OS package systems, replacing critcl's copies of Tcl headers
	with their own.

[enum]	Fixed issue #28. Added missing -mXX flags for linking at the
	linux-{32,64}-* targets.

[enum]	Fixed issue #27. Added missing platform definitions for
	various alternate linux and OS X targets.

[enum]	Fixed issue #32. Merged pull request by Andrew Shadoura.
	Various typos in documentation and comments.

[list_end]
