[comment {--- Standard trailer for all manpages in this module --}]
[section Authors]
Jean Claude Wippler, Steve Landers, Andreas Kupries

[section {Bugs, Ideas, Feedback}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such at [uri https://github.com/jcw/critcl].

Please also report any ideas for enhancements you may have for either
package and/or documentation.
