[comment {--- Standard trailer for all manpages in this module --}]
[section Authors]
Jean Claude Wippler, Steve Landers, Andreas Kupries

[section {Bugs, Ideas, Feedback}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such at
[uri {https://chiselapp.com/user/andreas_kupries/repository/CriTcl/reportlist}].

Please also report any ideas for enhancements you may have for either
package and/or documentation.

[para] [emph Note] that this is not critcl's official bug tracker, but
the repository where inofficial and experimental development of critcl
is taking place. It is the best which can be done because an official
bug tracker does not exist.
