[subsection {License Invoked}]

When writing packages it is always good manners to provide prospective
users with the license the package is under, so that they can decide
whether they truly want to use the package, or not.

[para] As critcl-based packages often consist of only a single file a
nice way of doing that is to embed the license in that file. By using
a critcl command, namely [cmd critcl::license] this information is
then also available to the critcl application, which can put it into a
standard location, i.e. [file license.terms], of the generated
packages.

[para]
[emph {I currently have no specific example to demonstrate the command.}]
